/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as TailorsRouteImport } from './routes/tailors.tsx'
import { Route as SettingsRouteImport } from './routes/settings.tsx'
import { Route as RegisterRouteImport } from './routes/register.tsx'
import { Route as PaymentsRouteImport } from './routes/payments.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as CustomersRouteImport } from './routes/customers.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index.tsx'
import { Route as TailorOrdersRouteImport } from './routes/tailor.orders.tsx'
import { Route as ResetPasswordTokenRouteImport } from './routes/resetPassword.$token.tsx'
import { Route as OrdersNewRouteImport } from './routes/orders.new.tsx'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId.tsx'
import { Route as AdminUsersRouteImport } from './routes/admin.users.tsx'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders.tsx'

const TailorsRoute = TailorsRouteImport.update({
  id: '/tailors',
  path: '/tailors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorOrdersRoute = TailorOrdersRouteImport.update({
  id: '/tailor/orders',
  path: '/tailor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/resetPassword/$token',
  path: '/resetPassword/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tailors': typeof TailorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/resetPassword/$token': typeof ResetPasswordTokenRoute
  '/tailor/orders': typeof TailorOrdersRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tailors': typeof TailorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/resetPassword/$token': typeof ResetPasswordTokenRoute
  '/tailor/orders': typeof TailorOrdersRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/tailors': typeof TailorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/resetPassword/$token': typeof ResetPasswordTokenRoute
  '/tailor/orders': typeof TailorOrdersRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/customers'
  | '/dashboard'
  | '/forgot-password'
  | '/login'
  | '/payments'
  | '/register'
  | '/settings'
  | '/tailors'
  | '/admin/orders'
  | '/admin/users'
  | '/orders/$orderId'
  | '/orders/new'
  | '/resetPassword/$token'
  | '/tailor/orders'
  | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/customers'
  | '/dashboard'
  | '/forgot-password'
  | '/login'
  | '/payments'
  | '/register'
  | '/settings'
  | '/tailors'
  | '/admin/orders'
  | '/admin/users'
  | '/orders/$orderId'
  | '/orders/new'
  | '/resetPassword/$token'
  | '/tailor/orders'
  | '/orders'
  id:
  | '__root__'
  | '/'
  | '/customers'
  | '/dashboard'
  | '/forgot-password'
  | '/login'
  | '/payments'
  | '/register'
  | '/settings'
  | '/tailors'
  | '/admin/orders'
  | '/admin/users'
  | '/orders/$orderId'
  | '/orders/new'
  | '/resetPassword/$token'
  | '/tailor/orders'
  | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TailorsRoute: typeof TailorsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  TailorOrdersRoute: typeof TailorOrdersRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailors': {
      id: '/tailors'
      path: '/tailors'
      fullPath: '/tailors'
      preLoaderRoute: typeof TailorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor/orders': {
      id: '/tailor/orders'
      path: '/tailor/orders'
      fullPath: '/tailor/orders'
      preLoaderRoute: typeof TailorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword/$token': {
      id: '/resetPassword/$token'
      path: '/resetPassword/$token'
      fullPath: '/resetPassword/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TailorsRoute: TailorsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminUsersRoute: AdminUsersRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  TailorOrdersRoute: TailorOrdersRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
